@startuml
actor player

player ->> server ++ : /chess/start(object) 
server -> "exercise-chess" ++ : getMoves(object, object)

"exercise-chess"->"exercise-chess"++: mapPiece(string)
"exercise-chess" --> "exercise-chess" -- : string
"exercise-chess"->"exercise-chess"++: possibleMoves(string)
"exercise-chess" --> "exercise-chess" -- : array

"exercise-chess"->"exercise-chess"++: canWhitAttack(string)
"exercise-chess" --> "exercise-chess" -- : boolean


"exercise-chess"->"exercise-chess"++: canBlackAttack(string)
"exercise-chess" --> "exercise-chess" -- : boolean


"exercise-chess" --> server --: array, array, boolean, boolean

server ->> MongoDB ++ : logResult(method, input, output)
MongoDB -->> server -- : result | error
server -->> player -- : result object

database MongoDB
@enduml